export const allProducts = [
    { id: 1, name: 'Gấu Bông Mèo Nằm Lười', price: '250.000đ', image: 'https://placehold.co/600x600/f8c3c8/663349?text=Mèo+Lười', description: 'Chú mèo bông siêu mềm mịn, nằm lười biếng chỉ chờ bạn ôm. Một người bạn đồng hành tuyệt vời cho những giấc mơ ngọt ngào.' },
    { id: 2, name: 'Bình Nước Cầu Vồng Pastel', price: '180.000đ', image: 'https://placehold.co/600x600/c7ceea/663349?text=Bình+Nước', description: 'Mang cả cầu vồng theo bên bạn mỗi ngày với chiếc bình nước màu pastel xinh xắn. Giữ nhiệt tốt và an toàn cho sức khỏe.' },
    { id: 3, name: 'Đèn Ngủ Hình Trăng Sao', price: '320.000đ', image: 'https://placehold.co/600x600/fdeec9/663349?text=Đèn+Ngủ', description: 'Biến căn phòng của bạn thành một bầu trời đêm đầy sao với chiếc đèn ngủ hình trăng khuyết lung linh, huyền ảo.' },
    { id: 4, name: 'Set Sticker Hoạt Hình', price: '50.000đ', image: 'https://placehold.co/600x600/d4edda/663349?text=Sticker', description: 'Bộ sưu tập sticker với vô vàn hình ảnh ngộ nghĩnh, giúp bạn thỏa sức trang trí sổ tay, laptop và mọi vật dụng yêu thích.' },
    { id: 5, name: 'Túi Vải Tote Gấu Trúc', price: '150.000đ', image: 'https://placehold.co/600x600/e8e8e8/663349?text=Túi+Tote', description: 'Chiếc túi tote tiện dụng với hình gấu trúc đáng yêu, vừa thân thiện với môi trường, vừa là phụ kiện thời trang cá tính.' },
    { id: 6, name: 'Ốp Lưng Điện Thoại Thỏ Bảy Màu', price: '120.000đ', image: 'https://placehold.co/600x600/c3f8f2/663349?text=Ốp+Lưng', description: 'Bảo vệ dế yêu của bạn bằng chiếc ốp lưng thỏ bảy màu siêu cute, chất liệu silicon dẻo chống va đập tốt.' },
    { id: 7, name: 'Sổ Tay Bìa Lông Xù', price: '95.000đ', image: 'https://placehold.co/600x600/f8d7da/663349?text=Sổ+Tay', description: 'Cuốn sổ tay với bìa lông xù mềm mại, tạo cảm hứng cho bạn ghi lại những ý tưởng và khoảnh khắc đáng nhớ.' },
    { id: 8, name: 'Dép Bông Đi Trong Nhà', price: '170.000đ', image: 'https://placehold.co/600x600/d1e7dd/663349?text=Dép+Bông', description: 'Giữ ấm cho đôi chân của bạn với đôi dép bông êm ái, giúp bạn thư giãn tuyệt đối mỗi khi ở nhà.' },
    { id: 9, name: 'Bút Mực Nước Dễ Thương', price: '25.000đ', image: 'https://placehold.co/600x600/d1cde7/663349?text=Bút+Mực', description: 'Những chiếc bút mực nước với thiết kế độc đáo, giúp việc ghi chép trở nên thú vị và đầy màu sắc hơn.' },
    { id: 10, name: 'Móc Khóa Heo Con', price: '45.000đ', image: 'https://placehold.co/600x600/f6dce5/663349?text=Móc+Khóa', description: 'Chiếc móc khóa heo con xinh xắn sẽ là điểm nhấn đáng yêu cho chùm chìa khóa hoặc chiếc ba lô của bạn.' },
    { id: 11, name: 'Băng Đô Tai Mèo', price: '60.000đ', image: 'https://placehold.co/600x600/fcf4dd/663349?text=Băng+Đô', description: 'Phụ kiện không thể thiếu cho các buổi tiệc hay đơn giản là khi bạn muốn hóa thân thành một chú mèo tinh nghịch.' },
    { id: 12, name: 'Tất Vớ Cổ Ngắn Trái Bơ', price: '35.000đ', image: 'https://placehold.co/600x600/e2f0cb/663349?text=Tất+Vớ', description: 'Đôi vớ cổ ngắn với họa tiết trái bơ ngộ nghĩnh, mang lại sự thoải mái và phong cách cho đôi chân của bạn.' }
];
